### PR TITLE
Fixed memory leak when reading character cards.

### PR DESCRIPTION
**Pull request by takahiro0327**
Fixed a bug that caused character card data to leak.
Please merge if it looks OK.

One of the following causes.
https://github.com/ManlyMarco/Illusion_BrowserFolders/issues/35

~~Checked in KK/KKS, memory keeps increasing in KK when clicking [Refresh thumbnails].~~
~~Something is still leaking.~~ In KKS the memory increase stopped.
I must have missed something, it was fixed in KK too.

Before: Each click increases the memory used by 200 MB.
leak_before

After:
leak_after

### CODE REVIEW

**Review by ManlyMarco — APPROVED** [review]

**Comment by dakensil** [comment]
Hi @takahiro0327 @ManlyMarco will this fix be added in a BrowserFolders or IllusionFixes update?

**Comment by ManlyMarco** [comment]
This is an API change and only requires update to the API plugin.

**Comment by takahiro0327** [comment]
[KKSAPI.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/14548261/KKSAPI.zip)
[KKAPI.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/14548265/KKAPI.zip)

**Comment by dakensil** [comment]
> [KKSAPI.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/14548261/KKSAPI.zip) [KKAPI.zip](https://github.com/IllusionMods/IllusionModdingAPI/files/14548265/KKAPI.zip)

Do you have the API fix for HS2?

**Comment by takahiro0327** [comment]
I know you've probably solved the problem, but just in case, I'll leave you with a link.
HS2 zip is also available at
https://github.com/IllusionMods/IllusionModdingAPI/releases

**Pull request merged**
