### PR TITLE
Scrolling feature  (workaround fixed)

### PR DESCRIPTION
**Pull request by jalil49**
uncertain how scrolling affects newSlotTransform as the unhooked controls are not removed nor are the correct ones applied

### CODE REVIEW

**Comment by ManlyMarco** [comment]
What's the reason for MakerIntSlider, especially when it still works on a float value? You can do the same with normal slider and custom StringToValue + Mathf.Round on output.

**Comment by jalil49** [comment]
Ya it was dumb of me to make a whole new slider, got a weird issue where it defaulted to 23 for some reason, so added some lines of code and added the wholenumber property.

**Comment by jalil49** [comment]
left some additional code, feel free to remove it
A. for shit's and giggles
B. potential future debugging

**Comment by jalil49** [comment]
also not sure if the lines of code to fix the 23 default should be allowed to run even when not whole numbers

**Comment by ManlyMarco** [comment]
Looks good to me

**Comment by jalil49** [comment]
there is an issue, I added a 2nd copy of a line and forgot to remove it at the bottom of adding the scroll,                 CreateCustomControlsInSubCategory(slotTransform, _accessoryWindowEntries);

**Pull request merged**
